# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app.ui'
#
# Created: Fri Oct 10 22:52:17 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.box_high = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_high.setObjectName("box_high")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_high)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.box_low = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_low.setObjectName("box_low")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_low)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.load_box_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.load_box_button.setObjectName("load_box_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.load_box_button)
        self.set_box_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.set_box_button.setObjectName("set_box_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.set_box_button)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(210, 10, 160, 80))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.stock_code = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.stock_code.setObjectName("stock_code")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stock_code)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.amount_a = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.amount_a.setObjectName("amount_a")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.amount_a)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.amount_b = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.amount_b.setObjectName("amount_b")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.amount_b)
        self.tradelogs = QtWidgets.QTextBrowser(self.centralwidget)
        self.tradelogs.setGeometry(QtCore.QRect(10, 130, 501, 321))
        self.tradelogs.setObjectName("tradelogs")
        self.minutebars = QtWidgets.QTextBrowser(self.centralwidget)
        self.minutebars.setGeometry(QtCore.QRect(520, 130, 331, 321))
        self.minutebars.setObjectName("minutebars")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 81, 16))
        self.label_6.setObjectName("label_6")
        self.current_price = QtWidgets.QLineEdit(self.centralwidget)
        self.current_price.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.current_price.setObjectName("current_price")
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setGeometry(QtCore.QRect(380, 10, 111, 23))
        self.apply_button.setObjectName("apply_button")
        self.logs = QtWidgets.QTextBrowser(self.centralwidget)
        self.logs.setGeometry(QtCore.QRect(385, 41, 471, 51))
        self.logs.setObjectName("logs")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Box high"))
        self.label_2.setText(_translate("MainWindow", "Box low"))
        self.load_box_button.setText(_translate("MainWindow", "Load Box"))
        self.set_box_button.setText(_translate("MainWindow", "Set Box"))
        self.label_3.setText(_translate("MainWindow", "Stock code"))
        self.label_4.setText(_translate("MainWindow", "Amount A"))
        self.label_5.setText(_translate("MainWindow", "Amount B"))
        self.label_6.setText(_translate("MainWindow", "Current price"))
        self.apply_button.setText(_translate("MainWindow", "Apply config"))

